// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SelfCheckoutMachine.Model;

#nullable disable

namespace SelfCheckoutMachine.Migrations
{
    [DbContext(typeof(CurrencyContext))]
    partial class CurrencyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SelfCheckoutMachine.Model.Denomination", b =>
                {
                    b.Property<string>("Value")
                        .HasColumnType("varchar(255)");

                    b.Property<uint>("Amount")
                        .HasColumnType("int unsigned");

                    b.HasKey("Value");

                    b.ToTable("Denominations");

                    b.HasData(
                        new
                        {
                            Value = "5",
                            Amount = 0u
                        },
                        new
                        {
                            Value = "10",
                            Amount = 0u
                        },
                        new
                        {
                            Value = "20",
                            Amount = 0u
                        },
                        new
                        {
                            Value = "50",
                            Amount = 0u
                        },
                        new
                        {
                            Value = "100",
                            Amount = 0u
                        },
                        new
                        {
                            Value = "200",
                            Amount = 0u
                        },
                        new
                        {
                            Value = "500",
                            Amount = 0u
                        },
                        new
                        {
                            Value = "1000",
                            Amount = 0u
                        },
                        new
                        {
                            Value = "2000",
                            Amount = 0u
                        },
                        new
                        {
                            Value = "5000",
                            Amount = 0u
                        },
                        new
                        {
                            Value = "10000",
                            Amount = 0u
                        },
                        new
                        {
                            Value = "20000",
                            Amount = 0u
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
